version: "5"

services:
  robbot:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgres
    environment:
      - DB_PROVIDER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
      - REDDIT_ID=${REDDIT_ID}
      - REDDIT_SECRET=${REDDIT_SECRET}
      - REDDIT_AGENT=${REDDIT_AGENT}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - TESTING_GUILD_ID=${TESTING_GUILD_ID}
      - TESTING_CHANNEL_ID=${TESTING_CHANNEL_ID}

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}