version: "5"

services:
  robbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: robbot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - REDDIT_ID=${REDDIT_ID}
      - REDDIT_SECRET=${REDDIT_SECRET}
      - REDDIT_AGENT=${REDDIT_AGENT}
      - TESTING_GUILD_ID=${TESTING_GUILD_ID}
      - TESTING_CHANNEL_ID=${TESTING_CHANNEL_ID}