version: "5"

services:
  robbot-pb:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./pb/data:/pb/pb_data
      - ./pb/migrations:/pb/pb_migrations
    ports:
      - "8080:8080"
    