version: "5"

services:
  robbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: robbot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - REDDIT_ID=${REDDIT_ID}
      - REDDIT_SECRET=${REDDIT_SECRET}
      - REDDIT_AGENT=${REDDIT_AGENT}
      - TESTING_GUILD_ID=${TESTING_GUILD_ID}
      - TESTING_CHANNEL_ID=${TESTING_CHANNEL_ID}

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=robbot