# Simple workflow for deploying static content to GitHub Pages
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test

on:
  # Runs on pushes targeting the default branch
  push:
    paths:
      - "**.py"
      - "**/test.yml"

jobs:
  test:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv flake8 pytest
          pipenv install --deploy
      - name: Test with pytest
        run: |
          pytest
